Exercise10.class : Exercise10.java Buttons.class Canvas.class Data.class DesignElement.class ElementPanel.class FileIO.class FillPanel.class Palette.class SelectedPanel.class StrokePanel.class Design6.class Image.class
        javac Exercise10.java

Canvas.class : Canvas.java
        javac Canvas.java

Data.class : Data.java
        javac Data.java

DesignElement.class : DesignElement.java
        javac DesignElement.java

FileIO.class : FileIO.java
        javac FileIO.java

Buttons.class : Buttons.java
        javac Buttons.java

ElementPanel.class : ElementPanel.java
        javac ElementPanel.java

FillPanel.class : FillPanel.java
        javac FillPanel.java

Palette.class : Palette.java
        javac Palette.java

SelectedPanel.class : SelectedPanel.java
        javac SelectedPanel.java

StrokePanel.class : StrokePanel.java
        javac StrokePanel.java

Design6.class : Design6.java
        javac Design6.java

Image.class : Image.java
        javac Image.java

clean :
        rm *.class

# submit : Buttons.java Canvas.java Data.java DesignElement.java ElementPanel.java Exercise10.java FileIO.java FillPanel.java Palette.java SelectedPanel.java StrokePanel.java Design6.java Image.java makefile mendozaE10.txt mendozaE10.jpg mendozaE106.jpg mendozaE10.pdf \
#        rm -rf mendozaE10 \
#        mkdir mendozaE10 \
#        cp Buttons.java mendozaE10 \
#        cp Canvas.java mendozaE10 \
#        cp Data.java mendozaE10 \
#        cp Design6.java mendozaE10 \
#        cp DesignElement.java mendozaE10 \
#        cp ElementPanel.java mendozaE10 \
#        cp Exercise10.java mendozaE10 \
#        cp FileIO.java mendozaE10 \
#        cp FillPanel.java mendozaE10 \
#        cp Image.java mendozaE10 \
#        cp Palette.java mendozaE10 \
#        cp SelectedPanel.java mendozaE10 \
#        cp StrokePanel.java mendozaE10 \
#        cp makefile mendozaE10 \
#        cp mendozaE10.txt mendozaE10 \
#        cp mendozaE10.jpg mendozaE10 \
#        cp mendozaE106.jpg mendozaE10 \
#        cp mendozaE10.pdf mendozaE10 \
#        tar cfvz mendozaE10.tgz mendozaE10 \
#        cp mendozaE10.tgz ~tiawatts/cs375drop \
